### ISSUE TITLE
Unable to use command combination

### ISSUE THREAD

**Issue by edawine** [laymonage/AidenBot#6]
The command "aes" is supposed to be usable with other commands, like "shout". So when I do "/shout /aes hello", I should have "ＨＥＬＬＯ" as the output. Instead, I got "/AES HELLO", and the other combinations produced these incorrect outputs.

**Comment by laymonage** [comment]
You need to use /cmb to combine commands.

**Comment by edawine** [comment]
Ah okay then, I missed that in the help description. Thanks!
