### ISSUE TITLE
Unable to use command stalkig

### ISSUE THREAD

**Issue by edawine** [laymonage/AidenBot#8]
Every time /stalkig is invoked on public username, it outputs Invalid format. The example provided in the help menu also does not work.

**Comment by laymonage** [comment]
Hmm, looks like Instagram has blocked access to their undocumented `.json` api. We can't even access [@instagram](https://www.instagram.com/instagram/?__a=1)'s data.
I'll have to look for another way to fetch the data. Thanks for reporting.

**Comment by laymonage** [comment]
According to [this answer](https://stackoverflow.com/a/45348715), there's a JSON embedded in a user's profile page that contains some of the data we need. I've managed to browse through it and obtained the URLs to the pictures. I'll update the stalkig function soon.

**Comment by laymonage** [comment]
Fixed in https://github.com/laymonage/AidenBot/commit/a89b771e8f07f83bed767bc3faa6b3c28a8391ac.

**Comment by edawine** [comment]
Tested and working as expected. Thanks!

**Comment by laymonage** [comment]
Whoops. I only tested it on one account and looks like I still have to change some things to make it work properly.

**Comment by laymonage** [comment]
Done. Private account detection wasn't working properly and it's fixed in https://github.com/laymonage/AidenBot/commit/893048e694d684aac6bb3bd655e24db5d4fca04c.
