### ISSUE TITLE
Command "stalkig" not working

### ISSUE THREAD

**Issue by edawine** [laymonage/AidenBot#9]
The command does not work again, maybe Instagram has changed the API (like #8)?

**Comment by laymonage** [comment]
They change things all the time :laughing:
Try it now.

I can make the module choose the correct script on its own, but it'll be slower (I don't really know how much). In the mean time, hardcoding still works :man_shrugging:

**Comment by edawine** [comment]
I've confirmed the commit has fixed the issue, thanks!
